language: shell # minimal

os:
  - linux

dist: bionic

branches:
  only:
    - master
    - development

services:
  - docker

env:
  - SHA=$(git rev-parse --short=7 HEAD)

before_install:
  - |
    # build the image
    docker image build \
      --tag juliocesarmidia/envoy-proxy-01:latest \
      --tag juliocesarmidia/envoy-proxy-01:v1.0.0 \
      -f envoy.Dockerfile .

script:
  - |
    # shell linter
    docker container run --name shellcheck --rm -v "$PWD:/mnt" -w /mnt -it koalaman/shellcheck-alpine:stable shellcheck deploy.sh

after_success:
  - |
    echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

    docker image push juliocesarmidia/envoy-proxy-01:latest
    docker image push juliocesarmidia/envoy-proxy-01:v1.0.0
