version: "3.4"

services:
  proxy:
    container_name: proxy
    build:
      context: ./envoy/
      dockerfile: envoy.Dockerfile
    networks:
      envoymesh:
        aliases:
          - envoy
    ports:
      - "8000:80/tcp"
      - "9901:9901/tcp"

  api-v1:
    container_name: api-v1
    image: juliocesarmidia/http-simple-api:v1.0.0
    networks:
      envoymesh:
        aliases:
          - api
    environment:
      API_PORT: "9000"
      MESSAGE: "API v1"
    expose:
      - "9000"

  api-v2:
    container_name: api-v2
    image: juliocesarmidia/http-simple-api:v1.0.0
    networks:
      envoymesh:
        aliases:
          - api
    environment:
      API_PORT: "9000"
      MESSAGE: "API v2"
    expose:
      - "9000"

  api-v3:
    container_name: api-v3
    image: juliocesarmidia/http-simple-api:v1.0.0
    networks:
      envoymesh:
        aliases:
          - api
    environment:
      API_PORT: "9000"
      MESSAGE: "API v3"
    expose:
      - "9000"

networks:
  envoymesh:
    driver: bridge
